# Версия синтаксиса файла
version: '3.8'

# Описываем сервисы (контейнеры)
services:
  # Первый сервис - веб-приложение
  web:
    # Собираем образ из Dockerfile в текущей папке
    build: .
    # Пробрасываем порт 8000 с нашей машины на порт 5000 внутри контейнера
    ports:
      - "8000:5000"
  
  # Второй сервис - база данных Redis
  redis:
    # Используем готовый официальный образ Redis с Docker Hub
    image: "redis:alpine"