version: '3.8'

services:
  ip-app:
    # Собирать образ из Dockerfile в текущей папке
    build: .
    # Пробрасываем порт 5001 с нашего компьютера на порт 5000 в контейнере
    ports:
      - "5001:5000"
    # === ГЛАВНАЯ ЧАСТЬ ЗАДАНИЯ ===
    # Устанавливаем переменную окружения TYPE
    environment:
      - TYPE=${TYPE}